#!/bin/sh

RunWeb=`/bin/get_key_value /etc/synoinfo.conf runweb`
if [ ! -d /var/services/web -o "x$RunWeb" != "xyes" ]; then
	echo "Please enable Web Station first." > $SYNOPKG_TEMP_LOGFILE
	exit 1
fi

exit 0
